services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: testDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: >
      sh -c "dotnet Task.Integration.Data.DbCreationUtility.dll -s 'Server=postgres_db;Port=5432;Database=testDb;Username=postgres;Password=12345678;' -p 'POSTGRE' && dotnet Task.Connector.dll"
    ports:
      - "8080:80"
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:
